<?php
// Version 2.0; Agreement

$txt['registration_agreement_body'] = 'Concorda, ao utilizar este fórum, que não irá publicar qualquer material que seja falso, difamatório, impreciso, abusivo, vulgar, odioso, ofensivo , obsceno, profano, sexualmente orientado, ameaçador, invasivo da privacidade de uma pessoa(s), material adulto, ou em violação de qualquer lei internacional, Europeia ou Portuguesa. Concorda também, não publicar qualquer material protegido por direitos de autor, a menos que possua os direitos sobre o mesmo, ou se tiver o consentimento escrito do proprietário do material protegido por direitos de autor. Spam, propaganda, esquemas de pishing, e solicitações com fins lucrativos são também proibidas neste fórum.

É impossível para os moderadores ou os proprietários deste fórum confirmar a validade de todas as mensagens. Lembre-se que nós não acompanhamos ativamente as mensagens publicadas e, como tal, não somos responsáveis ​​pelo conteúdo das mesmas. Não garantimos a exatidão, integridade ou utilidade de qualquer informação apresentada. As mensagens publicadas expressam as opiniões do autor, e não necessariamente a opinião deste fórum, do seu pessoal, das suas filiais , ou do proprietário deste fórum. Qualquer pessoa que sinta que uma dada mensagem publicada é censurável, é aconselhado a notificar de imediato um administrador ou moderador deste fórum. Os funcionários e/ou proprietário deste fórum reservam o direito de remover conteúdo, dentro de um prazo razoável, se for necessária a remoção dessa mesma publicação. Este é um processo manual, no entanto, por ser impossivel remover ou editar a mensagem imediatamente após a notificação ter sido enviada. Esta política aplica-se a todo o fórum, bem como às informações de perfis.

O utilizador é totalmente responsável pelo conteúdo das suas mensagens. Os proprietários deste fórum também reservam o direito de revelar a sua identidade (ou qualquer outra informação obtida neste serviço) no caso de uma queixa formal ou ação legal decorrente de qualquer situação causada pelo seu uso deste fórum.

Tem à disposição a habilidade de escolher o seu nome de utilizador. Deve então escolher um nome apropriado, que se encontre em conformidade com as regraas deste fórum. Concorda também em nunca partilhar a sua senha, para sua proteção e por razões de segurança. Concorda também em NUNCA utilizar a conta de outra pessoa por qualquer motivo. Recomendamos então que utilize uma senha complexa e única para a sua conta, para prevenir o roubo da mesma.

Depois de registar e efetuar o login neste fórum, será capaz de preencher um perfil detalhado. É de sua responsabilidade apresentar informações claras e precisas. Qualquer informação, que o proprietário do fórum ou a equipe, que seja considerada inadequada ou de natureza vulgar será removida, com ou sem aviso prévio. Sanções apropriadas podem ser aplicadas.

A cada publicação, o seu endereço de IP fica gravado, para a eventualidade de ser banido do fórum ou para contactarmos o seu ISP. Isso só acontecerá no caso de uma violação grave deste acordo.

Observe também que o software coloca um cookie , um arquivo de texto contendo bits de informação (como o username e a password) no cache do seu browser. Isto só é utilizado para manter a sua sessão ligada. O software não recolhe nem envia qualquer outro tipo de informação para o seu computador.';